#!/usr/bin/python

#this script pre-computes powers of 2 up to whatever you specify
# in the range() statement, and writes it to a file as a C++ array.
#
#Note that this assumes you are linking against the GNU GMP library

#change desired filename here
size=226
f = open('twos.h', 'a')
f.write('const mpz_class TWOS[] = {')
for i in range (0, size):
    f.write('mpz_class("'+str(2**i)+'",10),\n')
    #print "2 to the ",i," equals ",2**i #debug

f.write('};\n')
f.write('// array generated by precompute.py to 2^'+str(size))
f.close()
